export default {
    Skins: {
        "title": "Piel",
        "ligthwhite": "Muy clara",
        "white": "Clara",
        "brown": "Morena",
        "darkbrown": "Morena oscura",
        "black": "Muy oscura",
        "other": "Otro"
    },
    Hairs: {
        "title": "Cabello",
        "black": "Morocho",
        "darkbrown": "Castaño oscuro",
        "lightbrown": "Castaño claro",
        "darkblond": "Rubio oscuro",
        "lightblond": "Rubio claro",
        "red": "Pelirrojo",
        "bald": "Sin cabello",
        "other": "Otro"
    },
    Eyes: {
        "title": "Ojos",
        "green": "Verdes",
        "blue": "Azules",
        "grey": "Grises",
        "brown": "Marrones",
        "black": "Negros",
        "honey": "Miel",
        "lightblue": "Celeste",
        "other": "Otro"
    },
    Attributes: {
        "All": "Todos",
        "AttendCouples": "Atiendo parejas",
        "AttendMan": "Atiendo hombres",
        "AttendWomen": "Atiendo mujeres",
        "AttendTrans": "Atiendo trans",
        "Companion": "Acompañante",
        "Active": "Activo",
        "Active_": "Activa",
        "Pasive": "Pasivo",
        "Pasive_": "Pasiva",
        "Kisses": "Besos",
        "Threesomes": "Tríos",
        "Orgies": "Orgias",
        "Rains": "Lluvias",
        "Sado": "Sado",
        "Feet": "Pies",
        "Fisting": "Fisting",
        "Anal": "Anal",
        "Vaginal": "Vaginal",
        "Toys": "Juguetes",
        "Massages": "Masajes",
        "FreeTermination": "Terminación libre",
        "ChangingRoles": "Cambio de roles",
        "Lingerie": "Lencería",
    }
}